brana_cmf:
  rest_content_types:
    users:
      content_type: users
      serializer: Brana\CmfBundle\Store\Serializer\UserSerializer
      fields_keys: all
      fields:
        id:
          read_only: true
        from_date:
          format: d/m/Y
        password:
          serializer: Brana\CmfBundle\Store\Serializer\Field\ObscureSerializer
        username:
          required: true