brana_cmf:
    users:
        contenttype: users
        serializer: \Custom\Serializers\Pages
        fields_mode: '::getAllFields'
        create: '::create'
        fields:
            id:
                read_only: true