brana_cmf:
  rest_content_types:
    users:
      content_type: users
      serializer: Brana\CmfBundle\Store\Serializer\UserSerializer
      fields:
        id:
          read_only: true
        from_date:
          format: d/m/Y
        password:
          serializer: Brana\CmfBundle\Store\Serializer\Field\ObscureSerializer
          write_only: true
        username:
          required: true
        name:
          required: true
        hash:
          serializer: Brana\CmfBundle\Store\Serializer\Field\ObscureSerializer
    things:
      content_type: things
      serializer: Brana\CmfBundle\Store\Serializer\UserSerializer
      fields_keys: all
      fields: ~