FROM php:fpm
RUN apt-get update && apt-get install -y --no-install-recommends \
        git \
        zlib1g-dev \
        libxml2-dev \
        libzip-dev \
        librabbitmq-dev \
    && docker-php-ext-install \
        pdo_mysql \
        zip \
    && pecl install amqp \
    && docker-php-ext-enable amqp

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
COPY brana/ /var/www/brana
COPY build/brana-consume/ /var/www/scripts/
WORKDIR /var/www/brana/
ENTRYPOINT ["bash", "/var/www/scripts/message-consumer.sh"]