parameters:

services:
    _defaults:
        autowire: true 
        autoconfigure: true

    # Main module
    App\Main\Service\:
        resource: '../src/Main/Service/*'
    
    App\Main\Controller\:
        resource: '../src/Main/Controller/*'
        tags: ['controller.service_arguments']

    App\MessageHandler\:
        resource: '../src/MessageHandler/*'
        tags: ['messenger.message_handler']
    
    Brana\CmfBundle\Psr\ContentTypesConfig: '@App\Main\Service\ContentTypes'
    Brana\CmfBundle\Psr\BranaKernel: '@App\Main\Service\Brana'