parameters:
    private_key: '%env(string:APP_PRIVATE_KEY)%'
    public_key: '%env(string:APP_PUBLIC_KEY)%'

services:
    _defaults:
        autowire: true 
        autoconfigure: true

    Brana\CmfBundle\Store\Store:
        public: true

    Brana\CmfBundle\Store\Drivers\OrmDriver:
        public: true

    Brana\CmfBundle\Store\Drivers\Orm\StoreInteractor:
        public: true

    Brana\CmfBundle\Store\Drivers\Orm\SchemaProvider:
        public: true

    Brana\CmfBundle\Store\Drivers\Orm\Metadata\DriverMetadata: ~

    Brana\CmfBundle\Config\:
        resource: '../../Config/*'
        public: true

    Brana\CmfBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
        public: true

    Brana\CmfBundle\Command\:
        resource: '../../Command/*'
        tags: ['console.command']
        public: true

    Brana\CmfBundle\Auth\JwtBearerAuth:
        autowire: false
        arguments:
            - '%private_key%'
            - '%public_key%'
            - '@Brana\CmfBundle\Store\Store'
