users:
    entity: App\User\Entity
    manager: Brana\CmfBundle\Store\Manager\ContentManager
    engine: Orm
    name: users
    fields:
        id:
            type: integer
            pk: true
        username:
            type: slug
            nullable: false
        name:
            type: text
            nullable: false
        hash:
            type: text
            nullable: true
            length: 128
        email:
            type: text
        from_date:
            type: date
        is_admin:
            type: boolean
        type:
            type: choice
            values:
                - name: 'staff'
                  value: 1
                - name: 'contact'
                  value: 2
        things_rel:
            type: relation
            target: things
            relation_type: one-to-many

        # avatar:
        #     type: image
        #     extensions: [ gif, jpg, png ]
    default_status: published
    searchable: false