users:
    name: users
    fields:
        id:
            type: integer
        username:
            type: text
        name:
            type: slug
            uses: [ title ]
        password:
            type: text
        email:
            type: text
        # avatar:
        #     type: image
        #     extensions: [ gif, jpg, png ]
    default_status: published
    searchable: false
