# index
rest_index:
  path: /api/{contenttype}
  controller: App\Main\Controller\DefaultController::index
  methods:  [GET]

rest_retrieve:
  path: /api/{contenttype}/{slug}
  controller: App\Main\Controller\DefaultController::retrieve
  methods:  [GET]

rest_create:
  path: /api/{contenttype}
  controller: App\Main\Controller\DefaultController::create
  methods:  [POST]

rest_update:
  path: /api/{contenttype}/{slug}
  controller: App\Main\Controller\DefaultController::update
  methods:  [PUT]

rest_partial_update:
  path: /api/{contenttype}/{slug}
  controller: App\Main\Controller\DefaultController::partialUpdate
  methods:  [PATCH]

rest_destroy:
  path: /api/{contenttype}/{slug}
  controller: App\Main\Controller\DefaultController::destroy
  methods:  [DELETE]