# index
index:
  path: /api/{contenttype}
  controller: App\Main\Controller\DefaultController::index
  methods:  [GET]

retrieve:
  path: /api/{contenttype}/{slug}
  controller: App\Main\Controller\DefaultController::retrieve

create:
  path: /api/{contenttype}
  controller: App\Main\Controller\DefaultController::create
  methods:  [POST]

# rest api
# rest-index:
#    path: /api/{contenttype}
#    controller: App\Controller\Rest::index

# rest-retrieve:
#    path: /api/{contenttype}/{slug}
#    controller: App\Controller\Rest::retrieve

# rest-delete:
#    path: /api/{contenttype}/{slug}
#    controller: App\Controller\Rest::delete

# rest-update:
#    path: /api/{contenttype}/{slug}
#    controller: App\Controller\Rest::update

# # app builder
# app-builder:
#    path: /views/{contenttype}/{action}
#    controller: App\Controller\DefaultController::index

# # web dashboard
# dashboard:
#    path: /dashboard/{contenttype}/{action}
#    controller: App\Controller\DefaultController::index
